#!/bin/sh
#- !/usr/bin/env bash
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if test "$(git diff --cached --name-only --diff-filter=AR -z |
	LC_ALL=C tr -d '[ -~]\0')"; then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	exit 1
fi

echo "Current working directory is: ""$(pwd)"


# ASTYLE checking. For compatibility reasons we do NOT use the options file implicitly.
# Instead we disable the default behaviour (using a default or search-based option file)
# and parse the options from the options file into an options string.
# The .astylerc file should be formated with one option per line. Comments are O.K. and will be disregarded.

if ! ASTYLE=$(which astyle); then
	echo "[!] astyle not installed. Unable to check source file format policy." >&2
	exit 1
fi

ASTYLE_OPTIONS_FILE="src/lsddev/.astylerc"

test -f ${ASTYLE_OPTIONS_FILE} || {
	echo "[!] ${ASTYLE_OPTIONS_FILE} cannot be found. Unable to check source file format policy." >&2
	exit 1
}

OPTIONS="--project=none" #due to bug https://sourceforge.net/p/astyle/bugs/541/ and issues encountered when setting up the hook, we read the options manually from a file.


while read -r line; do
	# echo "DEBUG -  line: ${line}"
	if echo "${line}" | grep -q '^\#' || echo "${line}" | tr -d ' ' | grep -q '^$'; then
		# echo "DEBUG - skipped"
		continue
	else
		OPTION=$(echo "${line}" | awk -F"#" '{print $1}' | tr -d ' ')
		# echo "DEBUG - extracted option: ${OPTION}"
		OPTIONS="${OPTIONS} $OPTION"
	fi
done <${ASTYLE_OPTIONS_FILE}

# echo "DEBUG - Options: ${OPTIONS}"


RETURN=0

FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E "src/lsddev/.*\.(c|cpp|h|hpp)$")
for FILE in ${FILES}; do
	# echo "DEBUG - The command: ${ASTYLE} ${OPTIONS} --errors-to-stdout --dry-run ${FILE}"
	# check if the formated file differs from the unformatted file. Do not format here.
	NEEDS_FORMATTING=$(${ASTYLE} ${OPTIONS} --errors-to-stdout --formatted --dry-run ${FILE})
	# echo "DEBUG - var NEEDS_FORMATTING = ${NEEDS_FORMATTING}"
	if echo ${NEEDS_FORMATTING} | tr -d ' ' | grep -q '^$'; then #empty output
		echo "(OK) ${FILE} respects the agreed coding style."
		continue
	else
		echo "[!] ${FILE} does not respect the agreed coding style." >&2
		RETURN=1
	fi
done

if [ ${RETURN} -eq 1 ]; then
	echo "" >&2
	echo "Make sure you have run astyle on all files inside /src/lsddev with the following options from file ${ASTYLE_OPTIONS_FILE}:" >&2
	echo "${OPTIONS}" >&2
fi

exit ${RETURN}
