# Intention: Create PR to merge 8.0-beta into 8.0-beta-test-automation
#
# This workflow will automatically create a PR when updates on 8.0-beta are detected, updating any existing PR that is not yet closed.
# The PR is also automatically tested and, if the test is successful, it is automatically merged into the test automation branch.
name: "CI create/update PR [8.0-beta] -> [8.0-beta-test-automation]"

env:
  SOURCE_BRANCH: "origin/8.0-beta"
  TARGET_BRANCH: "8.0-beta-test-automation"
  CI_BRANCH: "CI/PR-8.0-beta--into--test-automation"

on:
  workflow_dispatch:      
  push:
    branches: [8.0-beta]

jobs:
  create-or-update-PR:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-target-branch
      uses: actions/checkout@v2
      with:
        ref: ${{ env.TARGET_BRANCH }}
    - name: merge-in-source-branch
      run: |
        git fetch --unshallow
        git config --global user.email "frederik.schaff@thinkcomplex.eu"
        git config --global user.name "Frederik Schaff"
        git merge --no-ff --no-commit $SOURCE_BRANCH        
    - name: create-PR for merge
      uses: FrederikSchaff/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Automatic PR [${{ env.SOURCE_BRANCH }}] to [${{ env.TARGET_BRANCH}} ]"
        body: "This PR has been created automatically and is updated each time the local fork of ${{ env.SOURCE_BRANCH }} is updated."
        branch: ${{ env.CI_BRANCH }}
        commit-message: "Sync: Merge upstream [$SOURCE_BRANCH] changes (automatic PR)"
        author: "Frederik Schaff <frederik.schaff@thinkcomplex.eu>"
        labels: CI/CD
        reviewers: FrederikSchaff
        update-pull-request-title-and-body: true
