# This is a basic workflow that is manually triggered
name: LMM build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      reasonToRun:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Provide a reason for the trigger'
        # Default value if no value is explicitly provided
        default: 'Full LMM Build'
        # Input has to be provided for the workflow to run
        required: true
        
jobs:
  build_LMM:
  
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
      fail-fast: false

    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Install linux dependencies
      if: {{ matrix.os == "linux" }}
      run: |
          sudo apt-get update
          sudo apt-get install build-essential
          sudo apt-get install gdb
          sudo apt-get install gnuplot-qt
          sudo apt-get install multitail
          sudo apt-get install zlib1g-dev
          sudo apt-get install tcl-dev
          sudo apt-get install tk-dev
          echo "✅ dependencies successfully installed"
    - name: Install windows dependencies
      if: {{ matrix.os == "windows" }}
      run: |
          echo "To do..."
          exit 1
    - name: Install macos dependencies
      if: {{ matrix.os == "macos" }}
      run: |
          echo "To do..."
          exit 1
    - name: Checkout and System Info
      uses: actions/checkout@v2
    - name: Get system info
      uses: kenchan0130/actions-system-info@master
      id: system-info
    - name: build LMM
      id: build-LMM
      run: |
        cd src
        make clean -f makefile-${{ matrix.os }}
        make -f makefile-${{ matrix.os }}
    
