 # This workflow keeps the 8.0 beta branch in sync with the upstream branch. Note: Force is used! (all changes to local 8.0 will be lost)
name: Synchronise 8.0 beta branch

on:
  workflow_dispatch:  
  schedule:
  - cron: 0 0 * * * # At the end of each day
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "marcov64/Lsd"
        source_branch: "8.0-beta"
        destination_branch: "8.0-beta"
        github_token: ${{ secrets.GITHUB_TOKEN }}
